https:
  port: 5000
  tls:
    "*.microtech.icu":
      key: ./certs/privkey.pem
      cert: ./certs/cert.pem
    "default":
      key: ./certs/privkey.pem
      cert: ./certs/cert.pem
admin:
  port: 9876
  host: localhost

apiEndpoints:
  api1:
    host: "*"
    paths: "/factura/*"
  api2:
    host: "*"
    paths: "/payment/*"
  api3:
    host: "*"
    paths: "/billsender/"
  api:
    host: "*"
    paths: "/*"

serviceEndpoints:
  backFacturacionService:
    url: "http://backfacturacion:3000"
  paymentService:
    url: "http://payment:3000"
  billSenderService:
    url: "http://billsender:3000"
 

policies:
  - proxy

pipelines:
  pipeline_1:
    apiEndpoints:
      - api1
    policies:
      - proxy:
          action:
            secure: false
            serviceEndpoint: backFacturacionService
            changeOrigin: true
  pipeline_2:
    apiEndpoints:
      - api2
    policies:
      - proxy:
          action:
            secure: false
            serviceEndpoint: paymentService
            changeOrigin: true
  pipeline_3:
    apiEndpoints:
      - api3
    policies:
      - proxy:
          action:
            secure: false
            serviceEndpoint: billSenderService
            changeOrigin: true
  