https:
  port: 5000
  tls:
    "*.microtech.icu":
      key: ./certs/privkey.pem
      cert: ./certs/cert.pem
    "default":
      key: ./certs/privkey.pem
      cert: ./certs/cert.pem
admin:
  port: 9876
  host: localhost

apiEndpoints:
  api1:
    host: "*"
    paths: "/shopcart/*"
  api2:
    host: "*"
    paths: "/payment/*"
  api3:
    host: "*"
    paths: "/bill/*"
  api4:
    host: "*"
    paths: "/products/*"
  api5:
    host: "*"
    paths: "/suppliers/*"
  api6:
    host: "*"
    paths: "/categories/*"
  api7:
    host: "*"
    paths: "/employees/*"

serviceEndpoints:
  backFacturacionService:
    url: "http://backfacturacion:3000"
  paymentService:
    url: "http://payment:3000"
  billSenderService:
    url: "http://microtech.icu:8888"
  backInventarioService:
    url: "http://backinventario:3000"
 

policies:
  - proxy

pipelines:
  pipeline_1:
    apiEndpoints:
      - api1
    policies:
      - proxy:
          action:
            secure: false
            serviceEndpoint: backFacturacionService
            changeOrigin: true
  pipeline_2:
    apiEndpoints:
      - api2
    policies:
      - proxy:
          action:
            secure: false
            serviceEndpoint: paymentService
            changeOrigin: true
  pipeline_3:
    apiEndpoints:
      - api3
    policies:
      - proxy:
          action:
            secure: false
            serviceEndpoint: billSenderService
            changeOrigin: true
  pipeline_4:
    apiEndpoints:
      - api4
      - api7
    policies:
      - proxy:
          action:
            secure: false
            serviceEndpoint: backInventarioService
            changeOrigin: true
  pipeline_5:
    apiEndpoints:
      - api5
    policies:
      - proxy:
          action:
            secure: false
            serviceEndpoint: backInventarioService
            changeOrigin: true
  pipeline_6:
    apiEndpoints:
      - api6
    policies:
      - proxy:
          action:
            secure: false
            serviceEndpoint: backInventarioService
            changeOrigin: true